# Generated by Django 4.1 on 2022-09-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
